# Generated by Django 4.1.2 on 2022-10-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='messageBody',
            field=models.TextField(verbose_name='Message Body'),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='userID',
            field=models.PositiveSmallIntegerField(verbose_name='User ID'),
        ),
    ]
