# Generated by Django 4.1.2 on 2022-10-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userquery_messagebody_alter_userquery_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp (UTC)'),
        ),
    ]
