# Generated by Django 4.1.2 on 2022-10-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userquery_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='urgency_status',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MED', 'MED'), ('HIGH', 'HIGH')], default='LOW', max_length=20),
        ),
    ]
