# Generated by Django 4.1.2 on 2022-10-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userquery_urgency_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='urgency_status',
            field=models.CharField(max_length=20),
        ),
    ]
