# Generated by Django 4.1.2 on 2022-10-29 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userquery_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='userquery',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
