# Generated by Django 4.1.2 on 2022-10-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_users_alter_userquery_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
