# Generated by Django 4.1.2 on 2022-10-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userquery_userid_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='resolved',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('Assigned', 'Assigned'), ('Open', 'Open')], default='Open', max_length=255),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='userID',
            field=models.PositiveSmallIntegerField(verbose_name='User ID'),
        ),
    ]
