# Generated by Django 4.1.2 on 2022-11-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userquery_resolved_alter_userquery_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=255)),
                ('userID', models.PositiveSmallIntegerField(verbose_name='User ID')),
                ('queries_handled', models.TextField()),
                ('query_response', models.TextField()),
            ],
        ),
    ]
