# Generated by Django 4.1.2 on 2022-11-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_agentresponse_queries_handled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentresponse',
            name='queries_handled',
            field=models.JSONField(default='NULL'),
        ),
    ]
